services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: jwt_auth_db
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build: .
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge
