spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false


  datasource:
    url: jdbc:mysql://localhost:3306/yourDB
    username: root
    password: yourPassword

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8080

